### ISSUE TITLE
Check against non SSL port

### ISSUE THREAD

**Issue by bobdob** [ChristopherSchultz/ssltest#2]
I ran across a system running clear text on port 443.  SSLTest doesn't handle this cleanly.  Please add a check to make sure the system is running SSL prior to testing the ciphers.

The following error message is received:
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at net.christopherschultz.ssltest.SSLTest.main(SSLTest.java:615)

**Comment by ChristopherSchultz** [comment]
How would you suggest that `SSLTest` check for a non-encrypted service running on a particular port?

**Comment by bobdob** [comment]
I'd figure attempt a connection using clear text protocols.  Probably a
simple "GET / HTTP/1.1"  If the port is open and fails to get clear text
data, it is likely encrypted.  If it gets data back, it should give a
warning and probably terminate.  There are some types like explicit SFTP,
but I don't think you want to add support for that.

**Comment by ChristopherSchultz** [comment]
What if the service running on that port isn't HTTP? It would be tough to read the response to determine if it was something "plain-text". If the service-provider (server) is already running an "incorrect" (plaintext) service on port 443 (documented as the standard HTTP-over-TLS service), then perhaps it's running something else entirely, like `rsync` or `CTBCPTP`?

I don't really want to go down that rabbit hole. This program tests for TLS handshakes, and a plain-text service will fail 100% of the time, as it should. This program has nothing to do with HTTP _at all_, so supporting plaintext HTTP services is really out of scope.

**Comment by bobdob** [comment]
It fails on clear text, but with an unclear error message.

Thanks anyway!
